### ISSUE TITLE
[Object Box] Checklist for Stable

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1625]
- [x] fix black screen flash when resuming the app from recents
- [x] fix issue with matching some contacts
- [ ] chats snapping in when opened
- [ ] Tapping notification for a chat doesn't open the chat
- [ ] Some pinned chats seem to go unpinned
- [x] Manually syncing messages only will pull the last 100 messages no matter the days
- [ ] last message preview says unknown group event sometimes for sent images
