### ISSUE TITLE
1.8.0 Final Checklist

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1891]
# Overview

Here is a list of things that need to be fixed/changed before the 1.8.0 release. We are so close! I've assigned you guys to these issues, but if you don’t want to do it, or don't think you can, just comment and I'll re-assign.

## Zach

- [x] Latest Text Preview doesn't update correctly for incoming messages (only for sent messages)
- [x] Notifications in the shade don't get removed if you open the chat for a new notification before the new notification disappears
- [x] Notifications in the shade won't get removed if you have the chat open, lock your phone, get a text from the same chat, then re-open the same chat by unlocking your phone
- [x] Fix timezone bug from Monica
- [x] Typing an incorrect password during setup will pop you back to the splash screen
- [x] Fix responsiveness of Pinned Rows slider
- [ ] When fully closed and having multiple notifications from different chats, tapping a chat notification will take you to the wrong chat (sometimes; hard to reproduce)

## Tanay

- [x] Image disappears after sending (and maybe downloading) an attachment. Will re-appear after a second.

## Joel

- [x] Fix spacing between message & reaction bar
- [x] Add `Reply` as a default context menu option when Private API is enabled (and Big Sur+)
- [x] Clean up Emoji Shortcut Widget (padding when subject is present)
- [x] Test Emoji Shortcut widget in reverse scrolling (if UX is better, keep it)
- [x] Make hitting enter while the Emoji Shortcut widget is visible select the highlighted emoji
- [x] Pinned chats are highlighted after leaving a chat. This needs to be limited to desktop/web

## Unassigned

- [x] Keyboard state does not get honored after closing message details (reaction popup)
- [ ] Dupe messages after leaving and re-entering chat (hard to reproduce)
- [x] Replying via a notification, then swiping it away throws an error and the reply is not sent
- [x] images load infinitely: be in chat list -> go to home screen -> receive image notification -> open chat via tapping notification -> image loads indefinitely. This is very hard to reproduce from my experience

**Comment by zlshames** [comment]
Can't reproduce this: `Replying via a notification, then swiping it away throws an error and the reply is not sent`. Seems to work for me

**Comment by zlshames** [comment]
I also can't reproduce this: `Latest Text Preview doesn't update correctly for incoming messages (only for sent messages)`. Not sure how or why I was running into it before
