### ISSUE TITLE
[1.10.0] Theme Rewrite Checklist

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2161]
- [x] Chat title boldness should be lowered
- [x] Letter spacing should be a good bit less
- [x] Settings/Search buttons on the chat list have dark backgrounds when they should be light/match the background
- [x] Font size for message bubbles needs to be increased
- [x] Lower the boldness of the chat timestamp days, i.e. `Today, 11:00 am`, "Today" is too bold. Comparing it to iOS, it should be barely bold. Like just a tiny itty bit
- [x] Change right carot character, `>` next to chat title in the conversation view to a character that looks more like the iOS carot character (less pointy, broader in a sense)
- [x] `Add Member` and `Show More` button icons in chat details page are not centered
- [x] The background circles for pinned chats on iOS theme should have a different color. One to distinguish it from the background and the avatar circles
- [x] Pinned chat avatars are not aligned correctly when on the same row as a chat with a two-line title
- [x] apply bubble font to text field
- [x] Line spacing needs to be reduced. This is the spacing between 2 lines, not between the letters
