### ISSUE TITLE
1.11 Checklist

### ISSUE THREAD

**Issue by tneotia** [BlueBubblesApp/bluebubbles-app#2283]
- [x] Rewrite `ChatBloc` - reduce logic significantly (only save to DB, don't update UI, consolidate methods)
- [x] Rewrite `MessageBloc` -  reduce logic significantly (only save to DB, don't update UI, consolidate methods)
- [x] Rewrite queues
- [x] Rewrite `LifeCycleManager`
- [x] Rewrite `NotificationManager`
- [x] Rewrite `ActionHandler`
- [x] Verify `ChatManager` / `ChatController` / `MessageManager` are in a good state (otherwise rewrite)
- [x] Rewrite methods in `Attachment`, `Message`, and `Chat` models (consider adding to the new Chat / Message / Attachment services?)
- [x] Consolidate helpers
   - [x] Remove unused methods
   - [x] Create standardized files for each helper type (e.g. string helper, color helper, etc)
 - [x] UI Rewrite
    - [x] Message view
       - [x] Reply lines
       - [x] Typing indicator
       - [x] Message popup (and related)
       - [x] Bubble colors
       - [x] Contact info + photo
       - [x] Message effects
       - [x] View past edits
    - [x] Chat creator
 - [x] See TODOs in code
 - [x] attributed body and message summary info samples for the following:
    - [x] Digital Touch
    - [x] Apple Music
    - [x] Apple Pay
    - [x] GamePigeon
    - [x] Any other imessage app thingy
    - [x] Message with multiple parts (ie, message, then attachment, then message, etc) with parts unsent and edited and reacted to and replied to and mentions and sticker applied - this will be kept as the holiest of all messages
    - [x] Reply to a message with a message with multiple parts (not sure how it determines which part of the message attaches as a reply)
 - [x] screenshots of all of the above, plus:
    - [x] chat details (for group chat)
- [x] full sync stack overflow
- [x] disable sending attachments when replying
- [x] verify sharing to app or direct chat works (when backgrounded AND fully closed)
- [x] verify opening chat from notif works (when backgrounded AND fully closed)
- [x] verify replying to notif works (when backgrounded AND fully closed)
- [x] verify mark as read from notif works (when backgrounded AND fully closed)
- [x] When in redacted mode, real contact names still show up in conversation previews with tapbacks
- [x] https://discord.com/channels/640229510662455326/746692766167334963/1051994193234501762
- [x] On my Z Fold 4 when clicking on an already open chat on the left this occurs consistently.

So far the animations are so sweet and just from a quick conversation with my GF she and I both can tell it's much faster and seemless. I'm loving it!

Another thing I noticed is that the typing indicator for when the other person is typing is only showing on the chat list and not in the chat.
- [x] This version is definitely smoother and nicer looking. Well done. 

Some feedback: Font Size Scaling bars would look better if they all had the same size and alignment.
Also, it would be nice to have a master slider that moved all of them at once.
- [x] Also removing a reaction doesn't display it removed
- [x] So a kinda weird thing that doesn't hurt anyone but in the latest Android app the "Attach recent photo" button gets multiplied a bunch if you go into the other attachments menu
- [x] material chat highlight is bugged
- [ ] I think that interactive message and blank messages are just redacted mode messing with links. Here it is with and without.
- [x] picture:
![image](https://user-images.githubusercontent.com/50850142/207385061-5b317cb3-0e63-44a8-92b0-a664ef459de2.png)
- [x] find ways to improve reliability of typing status - maybe check every so often that the chat is actually typing?
- [x] sending multiple attachments in one go is bugged
- [x] marking chat read is borked if read receipts off for that specific chat but auto mark private api on
- [x] Failed to render active chat issue
- [x] noticed a bug.  when you're in a chat, and the person responds, the app registers it as a new message and shows the number on the back arrow to indicate a new message.  even though the "new message" is the chat you're currently in and are looking at
- [x] Pick contact when adding person to gc doesnt work
- [x] Reply to a notification can send repeatedly - maybe send "reply to message" guid to dart and dont send if already replied to message?
- [x] material chat title still shows as bold even though read
- [x] cannot go from system - > brightness of current system theme
- [x] material theme status bar brightness light mode is borked
- [x] status indicators showing as none
- [x] more contrast on reply bubble text iOS 
- [x] smart replies don't do anything when tapped

**Comment by zlshames** [comment]
Here's my own list:

- [ ] Fix refresh rate configuration

**Comment by davlsb** [comment]
- Swipe settings are not unavailable but the settings for them still appear
- Dividers don't always render correctly? sometimes a line may be half missing:
![image](https://user-images.githubusercontent.com/56422634/205468679-9a0ffd74-729c-49c1-822f-807d68b2a3ef.png)
![image](https://user-images.githubusercontent.com/56422634/205468681-685bf849-e66f-4b71-a2dd-c6699ab462f9.png)

**Comment by gettingerr** [comment]
- [ ] Tablet Mode dubplicated in settings menu when in "Tablet Mode" on Galaxy Z Fold 4
![Screenshot_20221203_203657_BlueBubbles (Beta)](https://user-images.githubusercontent.com/20651244/205469832-905b18f2-2f26-4553-940c-0249f3f358d1.jpg)

**Comment by warmpigman** [comment]
When in a group chat, I should be able to edit/create a new contact by either holding down on their pfp/contact name or holding down on a message and having an option in the popup that can edit/create a new contact.

**Comment by b1ankusername** [comment]
- [ ] Desktop version forwarding breaks chat list access and renders app unusable when pressing back
![image](https://user-images.githubusercontent.com/100311639/205531420-ad5de61f-74f0-4f7c-8259-15fcfcb769e0.png)
![image](https://user-images.githubusercontent.com/100311639/205531466-bb5d3591-09a2-453f-8e47-c6a024c7ec15.png)

**Comment by zlshames** [comment]
> - [ ] Desktop version forwarding breaks chat list access and renders app unusable when pressing back
> ![image](https://user-images.githubusercontent.com/100311639/205531420-ad5de61f-74f0-4f7c-8259-15fcfcb769e0.png)
> ![image](https://user-images.githubusercontent.com/100311639/205531466-bb5d3591-09a2-453f-8e47-c6a024c7ec15.png)
> 

Errr is this just a bug with stable? If so, open another ticket. This is purely for the 1.11.0 alpha users

**Comment by jjoelj** [comment]
Couple things for material skin that I've noticed in Google messages

- [ ] show reply icon to the inside of message when showing reaction popup (in addition to swipe)
- [ ] swipe to reply should be default as well
- [ ] Messages that are sent but not yet delivered in latest message text are italicized
- [ ] Sent messages in latestmessagetext start with "You: "
- [ ] show message timestamps as <time> • Read/Delivered/Sent
- [ ] always show most recent message timestamp even if it is not from me
- [ ] Timestamps in convo view say "Now" up until 1 min "X min" until 59 min (I think), and then "hh:mm AM/PM" for the rest of the current day, then e.g "Wed 3:54 PM" until the previous current day of week, then, within a year, e.g "May 4, hh:mm PM", and everything else "MM/DD/YY hh:mm PM"
- [ ] Timestamps in chat list say "Just Now" instead of "Now", the "X min" are the same. Within a week, it's the 3-character day of week. Within the year, it's e.g. "Mar 3". Anything older is MM/DD/YY
- [ ] This might be harder: when the latest message is an attachment, the latest text says something like "picture" and a preview of the image shows in a square on the right of the convo tile. The date doesn't show.
- [ ] also there's a scroll to top button in the chat list once you scroll down

**Comment by zlshames** [comment]
My new checklist:

- [ ] nitpick: for sent videos, the audio button should be moved a little more left so it doesn't collide with the edge of the bubble
- [ ] nitpick: initials in avatars need to be 1 px lower (only in conversation view header)
