### ISSUE TITLE
Next Release Checklist (v1.14.0)

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2782]
# Bug fix Checklist

- [ ] remove flutter foreground task dep
- [ ] fix invalid double when reading URL preview payload data

```
[SyncManager] Incremental Sync Error: AsyncExecutorError: AsyncTask execution error
â”‚ -- Cause: FormatException: Invalid double
â”‚ 
â”‚ #0      double.parse (dart:core-patch/double_patch.dart:113)
â”‚ #1      new MediaMetadata.fromJson (package:bluebubbles/models/global/payload_data.dart:116)
â”‚ #2      new UrlPreviewData.fromJson (package:bluebubbles/models/global/payload_data.dart:78)
â”‚ #3      new PayloadData.fromJson.<anonymous closure> (package:bluebubbles/models/global/payload_data.dart:20)
â”‚ #4      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
â”‚ #5      ListIterator.moveNext (dart:_internal/iterable.dart:354)
â”‚ #6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
â”‚ #7      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
â”‚ #8      new List.of (dart:core-patch/array_patch.dart:39)
â”‚ #9      ListIterable.toList (dart:_internal/iterable.dart:224)
â”‚ #10     new PayloadData.fromJson (package:bluebubbles/models/global/payload_data.dart:20)
â”‚ #11     Message.dbPayloadData= (package:bluebubbles/models/io/message.dart:304)
â”‚ #12     getObjectBoxModel.<anonymous closure> (package:bluebubbles/objectbox.g.dart:1580)
â”‚ #13     EntityDefinition.objectFromData (package:objectbox/src/modelinfo/entity_definition.dart:43)
â”‚ #14     CursorHelper._deserializeObject (package:objectbox/src/native/bindings/helpers.dart:128)
â”‚ #15     CursorHelper.get (package:objectbox/src/native/bindings/helpers.dart:137)
â”‚ #16     Box.get.<anonymous closure> (package:objectbox/src/native/box.dart:350)
â”‚ #17     Store._runInTransaction (package:objectbox/src/native/store.dart:776)
â”‚ #18     InternalStoreAccess.runInTransaction (package:objectbox/src/native/store.dart:894)
â”‚ #19     Box.get (package:objectbox/src/native/box.dart:349)
â”‚ #20     ToOne.target (package:objectbox/src/relations/to_one.dart:84)
â”‚ #21     Attachment.merge (package:bluebubbles/models/io/attachment.dart:263)
â”‚ #22     syncAttachments (package:bluebubbles/helpers/backend/sync/sync_helpers.dart:119)
â”‚ #23     BulkSyncMessages.run.<anonymous closure> (package:bluebubbles/services/backend/sync/tasks/sync_tasks.dart:176)
â”‚ #24     Store.runInTransaction.<anonymous closure> (package:objectbox/src/native/store.dart:628)
â”‚ #25     Store._runInTransaction (package:objectbox/src/native/store.dart:776)
â”‚ #26     Store.runInTransaction (package:objectbox/src/native/store.dart:628)
â”‚ #27     BulkSyncMessages.run (package:bluebubbles/services/backend/sync/tasks/sync_tasks.dart:135)
```

- [ ] fix invalid double when matching chats to messages in the sync Messages async task
- [ ] fix back gesture issue when entering chat via notification

```
│ [SyncManager] Incremental Sync Error: AsyncExecutorError: AsyncTask execution error
│ -- Cause: FormatException: Invalid double
│ 
│ #0      ObjectVisitorError.throwIfError (package:objectbox/src/native/bindings/data_visitor.dart:58)
│ #1      Query.find (package:objectbox/src/native/query/query.dart:1080)
│ #2      syncMessages (package:bluebubbles/helpers/backend/sync/sync_helpers.dart:174)
│ #3      BulkSyncMessages.run.<anonymous closure> (package:bluebubbles/services/backend/sync/tasks/sync_tasks.dart:183)
```

- [ ] fix chat creator render issue causing participant list to be empty. The following error no longer occurs, but we should fix the underlying issue

```
BlueBubblesApp] Stacktrace: #0      List.first (dart:core-patch/growable_array.dart:344)
│ #1      ChatCreatorState.build.<anonymous closure>.<anonymous closure> (package:bluebubbles/app/layouts/chat_creator/chat_creator.dart:598)
│ #2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
│ #3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:938)
│ #4      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:868)
```

# Testing Checklist

- [ ] test new background service (without FCM)
- [ ] test new live logging and logging export capabilities
    - make sure no additional jank/lag is introduce

**Comment by zlshames** [comment]
I believe both invalid double errors were caused by the same "bad code". The one for the`.find()` call I think was the same error, but the stack trace was just concatenated maybe...

**Comment by zlshames** [comment]
cant seem to fix the back gesture causing the app to exit when opening via a notification. Might be a flutter bug, or we are doing something wrong. However, the Back Button Interceptor package had the same issue as using PopScope. Basically, the pop callback isnt being called, no matter what i try. It's not logging anything, even in the dispose function...
